on:
  push:
    branches:
      - master

jobs:
  test_a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create_a.sh
      - uses: actions/upload-artifact@v4
        with:
          name: test_a
          path: layers/

  test_b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create_b.sh
      - uses: actions/upload-artifact@v4
        with:
          name: test_b
          path: layers/

  test_c:
    runs-on: ubuntu-latest
    needs:
      - test_a
      - test_b
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test_a
          path: layers
      - uses: actions/download-artifact@v4
        with:
          name: test_b
          path: layers
      - run: find . | sort
